# Generated by Django 5.2.6 on 2025-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='date_saved',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='bookshelves',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='text_url',
            field=models.URLField(),
        ),
    ]
