# Generated by Django 5.2.6 on 2025-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_savedarticle_date_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='text_url',
            field=models.URLField(blank=True),
        ),
    ]
