# Generated by Django 5.2.6 on 2025-10-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_savedarticle_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='bookshelves',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='text_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
